[package]
name = "escpos-net"
version = "0.1.0"
edition = "2021"
authors = ["PhaSis <leojr.crassaris@hotmail.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
